{% set name = "django-simple-file-handler" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d3/11/ecf144e17b1fd8331da9035ba8bd822e59cdba508f47f56a3077bc283152/django_simple_file_handler-0.3.5.tar.gz
  sha256: 5e1b98c327c3b132658e580cf344b1ecaf501f47c0ad8017914c830cecbf9e40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=4.2
    - pillow >=8.3.0
    - xhtml2pdf >=0.2.5

test:
  imports:
    - django_simple_file_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonathanrickard/django-simple-file-handler
  summary: A Django app for storing and processing documents and images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
